export type PrintOptions = {
  primary?: string
  accent?: string
}

export function printHtml(title: string, html: string, opts: PrintOptions = {}) {
  const w = window.open('', '_blank', 'noopener,noreferrer,width=1200,height=900')
  if (!w) return
  const primary = opts.primary || '#3B82F6' // blue-500
  const accent = opts.accent || '#10B981' // emerald-500
  w.document.open()
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>${title}</title><style>
    :root { --primary: ${primary}; --accent: ${accent}; --ink:#0f172a; --muted:#64748b; --border:#e5e7eb; --row:#f8fafc; }
    *{box-sizing:border-box}
    body{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;color:var(--ink);-webkit-print-color-adjust:exact;print-color-adjust:exact;font-size:12px;line-height:1.5}
    .container{max-width:1024px;margin:0 auto;padding:24px}
    .header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}
    .brand{display:flex;align-items:center;gap:10px}
    .badge{background:var(--accent);color:white;font-weight:600;border-radius:999px;padding:4px 12px;font-size:11px}
    h1{margin:0 0 2px;font-size:20px;font-weight:700}
    h2{margin:16px 0 10px;font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}
    .card{border:1px solid var(--border);border-radius:12px;overflow:hidden;margin-bottom:16px;box-shadow:0 1px 2px rgba(0,0,0,.04)}
    .card-title{background:var(--primary);color:white;font-weight:600;padding:10px 14px;font-size:12px;letter-spacing:.02em}
    table{border-collapse:separate;border-spacing:0;width:100%;font-size:12px}
    thead th{background:var(--primary);color:white;text-align:left;font-weight:600;padding:10px 12px;border-right:1px solid rgba(255,255,255,.25)}
    thead th:first-child{border-top-left-radius:6px}
    thead th:last-child{border-right:none;border-top-right-radius:6px}
    tbody td{border-top:1px solid var(--border);padding:9px 12px}
    tbody tr:nth-child(even){background:var(--row)}
    .num{text-align:right}
    .muted{color:var(--muted)}
    footer{margin-top:18px;color:var(--muted);font-size:11px;text-align:center}
    @page { size: A4; margin: 12mm }
    @media print {
      body { background: white; }
      .container { padding: 0; }
    }
  </style></head><body><div class="container">${html}<footer>Generated by Finance Tracker</footer></div></body></html>`)
  w.document.close()
  w.focus()
  setTimeout(() => w.print(), 400)
}
